### ISSUE TITLE
Verificar quais estruturas e fucionalidades estão presentes em outras linguagens e são consideradas facilitadores de aprendizagem/execução

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/IDE-Lite#2]
1. Por que isso é mais fácil?
* Por que foi criado?
* No que é aplicado?
* Se assemelha algo mais natural pro ser humano?
* Verificar Engines?

**Comment by AdsonEsteves** [comment]
http://cacm.acm.org/blogs/blog-cacm/176450-python-is-now-the-most-popular-introductory-teaching-language-at-top-us-universities/fulltext

https://coderdojo.com/news/2015/03/20/top-5-programming-languages-for-beginners/

http://lifehacker.com/five-best-programming-languages-for-first-time-learners-1494256243

http://www.pcadvisor.co.uk/how-to/software/how-learn-write-computer-programs-3517275/

https://developers.google.com/blockly/

http://www.slant.co/topics/1907/~game-engines-for-beginners-and-non-programmers

http://venturebeat.com/2014/08/20/the-top-10-engines-that-can-help-you-make-your-game/

**Comment by AlissonSteffens** [comment]
Não esquece da página na wiki :p
