### ISSUE TITLE
Investigar Sintaxe, Curva de Aprendizagem, Trabalhos Publicados, recomendações, exemplos e IDEs

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/IDE-Lite#7]
- Investigar Sintaxe, Curva de Aprendizagem, Trabalhos Publicados, recomendações, exemplos e IDEs
- Python
- Ruby

**Comment by AdsonEsteves** [comment]
https://www.graphite.org/top-picks/best-apps-and-websites-for-learning-programming-and-coding

https://www.kidscodecs.com/resources/programming/education/

https://en.wikipedia.org/wiki/List_of_educational_programming_languages
